[package]
name = "backend"
version = "0.1.0"
authors = ["Tom Dymel <tomdymel@web.de>"]
edition = "2018"

[dependencies]
rocket = "*"
mysql = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sha3 = "*"
rand = "*"
lettre = "0.9"
lettre_email = "0.9"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
