version: '3.6'
services:
  mariadb:
    network_mode: host
    image: mariadb:10.4.8
    volumes:
    - ./../Database/patches:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_USER=mysql
    - MYSQL_PASSWORD=vagrant
    - MYSQL_ROOT_PASSWORD=vagrant
  nginx:
    network_mode: host
    build: ./nginx
    ports:
    - '80:80'
    - '443:443'
  postfix:
    network_mode: host
    image: juanluisbaptiste/postfix
    ports:
    - '25:25'
    environment:
    - SMTP_SERVER=smtp.gmail.com
    - SMTP_USERNAME=jaylapp@gmail.com
    - SMTP_PASSWORD=jaylapp123
    - SERVER_HOSTNAME=jaylapp.dev
