name: CI
on: [push]

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Linting
      - run: cd Webclient && npm install @angular/cli --next && npm install
      - run: cd Webclient && npm run-script lint
      - name: Building
      - run: cd Webclient && npm run-script build
      - name: Testing
      - run: cd Webclient && npm run-script test
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cd .github/actions/backend && docker-compose up -d
      - run: docker build -t docker_backend .github/actions/backend
      - run: docker run -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" --network host docker_backend