name: CI
on: [push]

jobs:
  build-webclient:
    name: Build Webclient
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install @angular/cli
      - run: cd Webclient && npm run ng build
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1.0.1
        with:
          toolchain: nightly
          command: build
          args: --manifest-path Backend/Cargo.toml --release --all-features