name: Webclient CI
on: [push]

jobs:
  building:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cd Webclient && npm install @angular/cli && npm run-script ng build
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cd Webclient && npm install @angular/cli && npm run-script ng lint
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/test-webclient